version: '2'
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: nginx.dev.docker
        volumes:
            - ./app:/var/www
            - /var/www/node_modules
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./app
            dockerfile: app.dev.docker
        volumes:
            - ./app:/var/www
        links:
            - database
            - cache
    webpack:
        build:
            context: ./app
            dockerfile: webpack.dev.docker
        volumes:
            - ./app:/var/www
            - /var/www/node_modules
        command: npm run watch
    socket:
        build:
            context: ./socket
            dockerfile: socket.dev.docker
        volumes:
            - ./socket:/usr/src/app
        ports:
            - "3000:3000"
    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "33061:3306"
    cache:
        image: redis:3.0
        ports:
            - "63791:6379"